### ISSUE TITLE
Transferring Ownership

### ISSUE THREAD

**Issue by ericgiannini** [shams-ahmed/StitchWorkshop#1]
@shams-ahmed May you please transfer ownership of this workshop over to me?

**Comment by ericgiannini** [comment]
https://www.youtube.com/watch?v=yqIbQI0WMys

**Comment by ericgiannini** [comment]
![image](https://user-images.githubusercontent.com/12617653/41579553-4c2ecb74-734c-11e8-91e9-23ca49104b5f.png)

**Comment by shams-ahmed** [comment]
<img width="738" alt="screen shot 2018-06-19 at 09 42 44" src="https://user-images.githubusercontent.com/2887472/41588514-e6b07df2-73a9-11e8-8335-c9d5feb324fb.png">

**Comment by ericgiannini** [comment]
@shams-ahmed Where do I go in the dashboard to find how to execute on the transfer?

**Comment by shams-ahmed** [comment]
my side complete, you have to figure this one. normally you just get a email to confirm.

**Comment by ericgiannini** [comment]
The link in the email, which I must have missed, expired. Transfer links last no longer than 24 hours. May you please reinitiate the transfer?

**Comment by shams-ahmed** [comment]
done

**Comment by ericgiannini** [comment]
@shams-ahmed, Oops! That repository transfer has expired.

**Comment by shams-ahmed** [comment]
lol it only 9 hours old... can you just fork the project.
